# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#   name = "github.com/x/y"
#   version = "2.4.0"
#
# [prune]
#   non-go = false
#   go-tests = true
#   unused-packages = true


[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.16.36"

[[constraint]]
  name = "github.com/carlosdp/twiliogo"
  version = "0.1.0"

[[constraint]]
  name = "github.com/go-playground/form"
  version = "3.1.4"

[[constraint]]
  name = "github.com/go-sql-driver/mysql"
  version = "1.4.1"

[[constraint]]
  name = "github.com/gorilla/mux"
  version = "1.7.0"

[[constraint]]
  name = "github.com/jmoiron/sqlx"
  version = "1.2.0"

[[constraint]]
  name = "github.com/rs/cors"
  version = "1.6.0"

[[constraint]]
  name = "github.com/rs/xid"
  version = "1.2.1"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.3.0"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.3.1"

[[constraint]]
  name = "github.com/ttacon/libphonenumber"
  version = "1.0.1"

[[constraint]]
  name = "github.com/urfave/negroni"
  version = "1.0.0"

[[constraint]]
  name = "go.opencensus.io"
  version = "0.19.0"

[[constraint]]
  name = "gopkg.in/go-playground/validator.v9"
  version = "9.27.0"

[[constraint]]
  name = "gopkg.in/njern/gonexmo.v1"
  version = "1.0.1"

[prune]
  go-tests = true
  unused-packages = true
